server:
  port: 3000

spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      start-listener: start-listener
    consumer:
      group-id: order-group
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF